// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIToolCall } from "./AIToolCall";

/**
 * Events emitted by the session to the frontend.
 */
export type SessionEvent = { "type": "streamStarted" } | { "type": "chunk", content: string, } | { "type": "responseComplete" } | { "type": "toolsRequested", calls: Array<AIToolCall>, } | { "type": "error", message: string, } | { "type": "cancelled" };
