// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlxQueryResult } from "./SqlxQueryResult";
import type { SqlxStatementResult } from "./SqlxStatementResult";

export type SqlxBlockExecutionResult = { "type": "Query", "data": SqlxQueryResult } | { "type": "Statement", "data": SqlxStatementResult };
