name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    paths:
      - "backend/**"
      - ".github/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: ${{ matrix.name }}
    runs-on: depot-ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: Test
            command: test
            components: ""
          - name: Check
            command: check
            components: ""
          - name: Clippy
            command: clippy
            components: clippy
          - name: Format
            command: fmt
            components: rustfmt
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
          cache-on-failure: true

      - name: Install latest rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: ${{ matrix.components }}

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run ${{ matrix.name }}
        working-directory: backend
        run: |
          case "${{ matrix.command }}" in
            test)
              cargo test
              ;;
            check)
              cargo check --no-default-features
              ;;
            clippy)
              cargo clippy -- -D warnings
              ;;
            fmt)
              cargo fmt -- --check
              ;;
          esac
